# Generated by Django 5.0.4 on 2024-05-03 10:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('profile_pic', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('borrowed_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 10, 5, 42, 720326, tzinfo=datetime.timezone.utc))),
                ('deadline', models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 10, 5, 42, 720326, tzinfo=datetime.timezone.utc))),
                ('borrower', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='librarian',
            old_name='email',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='course',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
