# Generated by Django 5.0.4 on 2024-05-03 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_materials_rename_email_librarian_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='borrower_course',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='borrower_year',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materials',
            name='borrowed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 12, 37, 58, 809711, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='materials',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 12, 37, 58, 809711, tzinfo=datetime.timezone.utc)),
        ),
    ]
