# Generated by Django 5.0.4 on 2024-05-03 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_materials_borrower_course_materials_borrower_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='borrowed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 12, 39, 15, 194262, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='materials',
            name='borrower',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='materials',
            name='borrower_course',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='materials',
            name='borrower_year',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='materials',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 12, 39, 15, 194262, tzinfo=datetime.timezone.utc)),
        ),
    ]
